version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres"
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    env_file:
      - .env
    build: 
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  postgres_data:
  