# Generated by Django 2.2.7 on 2019-11-28 03:08

import os
from django.db import migrations

def create_superuser(apps, schema_editor):
    from django.contrib.auth.models import User

    DJANGO_DB_NAME = os.environ.get('DJANGO_DB_NAME', "default")
    DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

    superuser = User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD)
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
